name: Test check-if-latest-lts-release action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'hazelcast-docker'
        uses: actions/checkout@v6
        with:
          repository: hazelcast/hazelcast-docker
          fetch-depth: 0

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: docker-actions

      - name: Run check-if-latest-lts-release 5.5.0
        id: check-if-latest-lts-release-5_5_0
        uses: ./docker-actions/check-if-latest-lts-release
        with:
          hz_version: 5.5.0

      - name: Run check-if-latest-lts-release 5.5.8
        id: check-if-latest-lts-release-5_5_8
        uses: ./docker-actions/check-if-latest-lts-release
        with:
          hz_version: 5.5.8

      - name: Run check-if-latest-lts-release 5.6.0
        id: check-if-latest-lts-release-5_6_0
        uses: ./docker-actions/check-if-latest-lts-release
        with:
          hz_version: 5.6.0

      - name: Test
        run: |
          set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)"

          TESTS_RESULT=0
          
          assert_equals() {
            local expected=$1
            local actual=$2
            local msg="Should be equal to ${expected}"
            assert_eq "$expected" "$actual" "$msg" && log_success "$msg" || TESTS_RESULT=$?
          }

          assert_equals "" "${{ steps.check-if-latest-lts-release-5_5_0.outputs.is_latest_lts }}"
          assert_equals "true" "${{ steps.check-if-latest-lts-release-5_5_8.outputs.is_latest_lts }}"
          assert_equals "" "${{ steps.check-if-latest-lts-release-5_6_0.outputs.is_latest_lts }}"

          assert_eq 0 "$TESTS_RESULT" "All tests should pass"
