name: Test check-if-latest-lts-release action

on:
  workflow_call:

jobs:
  test_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test scripts
        run: ./check-if-latest-lts-release/test_scripts.sh

  test:
    runs-on: ubuntu-latest
    env:
      github_repository_to_query: hazelcast/hazelcast-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run check-if-latest-lts-release 5.5.0
        id: jdks_5_5_0
        uses: ./check-if-latest-lts-release
          github_repository_to_query: ${{ env.github_repository_to_query }}
          hz_version: 5.5.0
          is_lts_override: true

      - name: Run check-if-latest-lts-release 5.5.8 no override
        id: jdks_5_5_8_no_override
        uses: ./check-if-latest-lts-release
          github_repository_to_query: ${{ env.github_repository_to_query }}
          hz_version: 5.5.8
          is_lts_override: false

      - name: Run check-if-latest-lts-release 5.5.8 override
        id: jdks_5_5_8_override
        uses: ./check-if-latest-lts-release
          github_repository_to_query: ${{ env.github_repository_to_query }}
          hz_version: 5.5.8
          is_lts_override: true

      - name: Run check-if-latest-lts-release 5.6.0
        id: jdks_5_6_0
        uses: ./check-if-latest-lts-release
          github_repository_to_query: ${{ env.github_repository_to_query }}
          hz_version: 5.6.0
          is_lts_override: true

      - name: Test
        run: |
          set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)"

          TESTS_RESULT=0
          
          assert_equals() {
            local expected=$1
            local actual=$2
            local msg="Should be equal to ${expected}"
            assert_eq "$expected" "$actual" "$msg" && log_success "$msg" || TESTS_RESULT=$?
          }

          assert_equals "false" "${{ steps.jdks_5_5_0.outputs.is_latest_lts }}"

          assert_equals "false" "${{ steps.jdks_5_5_8_no_override.outputs.is_latest_lts }}"
          assert_equals "true" "${{ steps.jdks_5_5_8_override.outputs.is_latest_lts }}"

          assert_equals "false" "${{ steps.jdks_5_6_0.outputs.is_latest_lts }}"

          assert_eq 0 "$TESTS_RESULT" "All tests should pass"
