name: Test test-image-size action

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test scripts
        run: ./test-image-size/test_scripts.sh

      - name: Run test-image-size
        uses: ./test-image-size
        with:
          image: hazelcast/hazelcast:5.0.1-slim
