name: Test check-if-latest-lts-release action

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      github_repository: hazelcast/hazelcast-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: debug
        run: echo "token is ${{ secrets.TOKEN }}"

      - name: Test scripts
        run: ./check-if-latest-lts-release/test_scripts.sh
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}

      - name: Run check-if-latest-lts-release 5.5.0
        id: jdks_5_5_0_no_override
        uses: ./check-if-latest-lts-release
        with:
          github_token: ${{ secrets.TOKEN }}
          github_repository: ${{ env.github_repository }}
          hz_version: 5.5.0
          is_lts_override: false

      - name: Run check-if-latest-lts-release 5.5.0
        id: jdks_5_5_0_override
        uses: ./check-if-latest-lts-release
        with:
          github_token: ${{ secrets.TOKEN }}
          github_repository: ${{ env.github_repository }}
          hz_version: 5.5.0
          is_lts_override: true

      - name: Run check-if-latest-lts-release 5.5.8
        id: jdks_5_5_8_no_override
        uses: ./check-if-latest-lts-release
        with:
          github_token: ${{ secrets.TOKEN }}
          github_repository: ${{ env.github_repository }}
          hz_version: 5.5.8
          is_lts_override: false

      - name: Run check-if-latest-lts-release 5.5.8
        id: jdks_5_5_8_override
        uses: ./check-if-latest-lts-release
        with:
          github_token: ${{ secrets.TOKEN }}
          github_repository: ${{ env.github_repository }}
          hz_version: 5.5.8
          is_lts_override: true

      - name: Run check-if-latest-lts-release 5.6.0
        id: jdks_5_6_0_no_override
        uses: ./check-if-latest-lts-release
        with:
          github_token: ${{ secrets.TOKEN }}
          github_repository: ${{ env.github_repository }}
          hz_version: 5.6.0
          is_lts_override: false

      - name: Run check-if-latest-lts-release 5.6.0
        id: jdks_5_6_0_override
        uses: ./check-if-latest-lts-release
        with:
          github_token: ${{ secrets.TOKEN }}
          github_repository: ${{ env.github_repository }}
          hz_version: 5.6.0
          is_lts_override: true

      - name: Test
        run: |
          set -o errexit -o nounset -o pipefail ${RUNNER_DEBUG:+-x}
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/assert.sh/main/assert.sh)"

          TESTS_RESULT=0
          
          assert_equals() {
            local expected=$1
            local actual=$2
            local msg="Should be equal to ${expected}"
            assert_eq "$expected" "$actual" "$msg" && log_success "$msg" || TESTS_RESULT=$?
          }

          assert_equals "" "${{ steps.jdks_5_5_0_no_override.outputs.is_latest_lts }}"
          assert_equals "true" "${{ steps.jdks_5_5_0_override.outputs.is_latest_lts }}"

          assert_equals "true" "${{ steps.jdks_5_5_8_no_override.outputs.is_latest_lts }}"
          assert_equals "true" "${{ steps.jdks_5_5_8_override.outputs.is_latest_lts }}"

          assert_equals "" "${{ steps.jdks_5_6_0_no_override.outputs.is_latest_lts }}"
          assert_equals "true" "${{ steps.jdks_5_6_0_override.outputs.is_latest_lts }}"

          assert_eq 0 "$TESTS_RESULT" "All tests should pass"
